### ISSUE TITLE
Desktop DeFi Wallet not synchronizing to 100%; stuck at 99.55% since days now

### ISSUE THREAD

**Issue by AmigoCrypto** [BirthdayResearch/defichain-app#1273] opened 2023-11-21 14:47 UTC
Defi Chain Wallet hasn't been able to sync to 100% since days now with the latest version: 4.0.0 in my case.

Reinstalling the app and implementing the latest snapshot are also not solving the issue.

**Comment by John-Gee** [comment] 2023-11-21 17:30
Same here.

I think that's hugely important to fix. Somehow I'm thinking the standard ain app would work and the wallet is not up to date, but maybe I'm wrong.

@thedoublejay

**Comment by thedoublejay** [comment] 2023-11-21 21:19
Hi, will be raising this to the team.

**Comment by krawalondl** [comment] 2023-11-23 06:03
Hello everyone,

I have the same problem and have been trying it out for over a week.
I have now got it syncronised with a manual snapshot, version: https://snapshot-de.mydefichain.com/snapshot-mainnet-3472230.tar.gz

It doesn't work with the automatically offered snapshot from the desktop wallet.
However, I now have another problem that the percentages are not displayed for all pool prizes. Sometimes it says n/a.

Best regards and many thanks in advance


Translated with www.DeepL.com/Translator (free version)

**Comment by John-Gee** [comment] 2023-11-23 17:16
I tried the latest build .6 with no improvement.
I'd like to try the snapshot above, but I don't know where it's from so...
It'd be nice to have supplementary snapshots for that kind of stuff to be able to debug/move forward.

**Comment by skutcher** [comment] 2023-11-23 19:02
> I tried the latest build .6 with no improvement. I'd like to try the snapshot above, but I don't know where it's from so... It'd be nice to have supplementary snapshots for that kind of stuff to be able to debug/move forward.

thats the default snapshot i get in the app. I used it 4 hours ago without any issues. So atm i have a fully synced desktop wallet using the latest linux app

**Comment by John-Gee** [comment] 2023-11-24 17:04
Yup I downloaded snapshot from https://defi-snapshots-us.s3.amazonaws.com/index.txt and indeed that worked with latest (not sure if it is different than 4.0 in that regard).

Thanks!

**Comment by John-Gee** [comment] 2024-01-18 12:50
I again had the same issue and a snapshot again fixed it.

**Comment by John-Gee** [comment] 2024-02-08 14:52
And again...
This is not great.
Is anyone still working on this? I see no commit since December...

@uzyn @thedoublejay

**Comment by thedoublejay** [comment] 2024-02-09 03:32
Hi @John-Gee,

I'm not part of the DeFiChain team currently. Tagging @fullstackninja864 @pierregee

**Comment by fullstackninja864** [comment] 2024-02-09 04:31
Hi @John-Gee, Can you follow these steps once
1. Make sure you are on latest [release](https://github.com/BirthdayResearch/defichain-app/releases/tag/v4.0.8)
2. Open Desktop wallet and from nav Menu > Wallet  > Reindex
3. Apply [snapshot](https://defi-snapshots.s3-ap-southeast-1.amazonaws.com/snapshot-mainnet-3705821.zip)
4. Wait for complete sync.
if you still having trouble in sync then please share App node log from Menu > Logs > App Logs and Menu > Logs > Node Logs

**Comment by AmigoCrypto** [comment] 2024-02-10 21:14
I went back to version 4.0.0 of the Windows Desktop app and this is working great again.

**Comment by John-Gee** [comment] 2024-02-11 00:43
@thedoublejay Oh I'm sorry to see that, I liked having you around.

@fullstackninja864 It does work with reapplying snapshot, that's ok, the issue is at some point the wallet stops synchronizing, without any kind of alert, so if I don't look at it I won't know. And if someone runs masternodes off that, well they would be as if offline then.

Thank you!

**Comment by fullstackninja864** [comment] 2024-02-12 04:00
@John-Gee, if the wallet encounters synchronization issues again, could you please share the application and node logs? Having access to this information would greatly assist in diagnosing the problem and finding a resolution.

Feel free to close this ticket if your current issue if fixed.  If the issue reoccurs again, feel free to open a new ticket for further assistance. Thank you!

**Comment by fullstackninja864** [comment] 2024-02-15 03:49
closing this issue because of inactivity, If the issue reoccurs again, feel free to open a new ticket.

**Closed by fullstackninja864** 2024-02-15 03:49 UTC
Labels: kind/feature, needs/triage
